# Generated by Django 4.2.4 on 2023-09-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_rename_name_category_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='name',
        ),
    ]
